# Generated by Django 4.2.5 on 2023-09-30 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('aadhar_card', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('voter_id_proof', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('marksheet', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
